document.writeln("<div class=\'footer\'>");
document.writeln("			<div class=\'footer_wrap\'>");
document.writeln("				<ul class=\'list-unstyled\'>");
document.writeln("					<li>");
document.writeln("						<p><a href=\'#\'>成人高考考试科目</a></p>");
document.writeln("						<p><a href=\'#\'>培训中心简介</a></p>");
document.writeln("						<p><a href=\'#\'>考试资讯</a></p>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<p>友情链接:</p>");
document.writeln("						<p><a href=\'#\'>广西招生考试院</a></p>");
document.writeln("						<p><a href=\'#\'>广西自学考试网上系统</a></p>");
document.writeln("						<p><a href=\'#\'>中国高等教育学生信息网</a></p>");
document.writeln("						<p><a href=\'#\'>中国教育网</a></p>");
document.writeln("						<p><a href=\'#\'>广西人事考试网</a></p>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>	");
document.writeln("		</div>");